Fix jira_user table to retry rate limit exceeded errors closes #68
turbot/steampipe-plugin-jira pull request #72
Opened 2022-11-21 12:27 UTC by misraved

# Example query results
<details>
  <summary>Results</summary>
  
```
Add example SQL query results here (please include the input queries as well)
```
</details>

2022-11-21 15:14 UTC, cbruno10 requested changes
@misraved I know this is still in draft, so some of my comments may be irrelevant already, but I left a few preliminary ones.

2022-11-21 15:14 UTC, cbruno10 commented on jira/table_jira_user.go
> +	return  groups, nil
Should there be an extra space here?

2022-11-21 15:14 UTC, cbruno10 commented on jira/table_jira_user.go
> +				RetryConfig: 		&plugin.RetryConfig{ ShouldRetryErrorFunc: shouldRetryError([]string{"429"})},
Spacing looks off here.

Also, if this works for this table, should we add a `RetryConfig` for all tables?

2022-11-21 15:14 UTC, cbruno10 commented on jira/errors.go
> +			log.Printf("[WARN] Received Rate Limit Error")
Is this log message actually printed out? I think it'd be better if we used the standard `plugin.Logger(ctx).LEVEL` function with the proper log message format, e.g., `functionName, message, data`.

Also, please check what we do in other plugins as reference.

2022-11-23 14:44 UTC, cbruno10 requested changes
@misraved Please see comments, thanks!

2022-11-23 14:44 UTC, cbruno10 commented on jira/errors.go
> +			plugin.Logger(ctx).Warn("Received Rate Limit Error")
This should be `Debug` level, not `Warn`. Also, we should use the standard log message format, e.g., https://github.com/turbot/steampipe-plugin-github/blob/main/github/errors.go#L18. I'm not sure what additional info we get (if any), but at the very least, we should include plugin/function name, and other standard args.

https://github.com/turbot/steampipe-plugin-jira/pull/72?notification_referrer_id=NT_kwDOALym4LM0ODg3MTE5ODgwOjEyMzYzNDg4&notifications_after=Y3Vyc29yOjI1#discussion_r1028166338

2022-11-23 14:44 UTC, cbruno10 commented on jira/plugin.go
> +		DefaultRetryConfig: &plugin.RetryConfig{ShouldRetryErrorFunc: shouldRetryError([]string{"429"})},
Was this question ever commented/resolved? https://github.com/turbot/steampipe-plugin-jira/pull/72#discussion_r1028165413

2022-11-23 15:35 UTC, misraved commented on jira/errors.go
> +			plugin.Logger(ctx).Warn("Received Rate Limit Error")
Sorry @cbruno10, had missed this reference to the GitHub plugin. I was following the error message format used in https://github.com/turbot/steampipe-plugin-steampipecloud/blob/main/steampipecloud/errors.go#L10

I have resolved it now 👍 .

2022-11-23 15:41 UTC, misraved commented on jira/plugin.go
> +		DefaultRetryConfig: &plugin.RetryConfig{ShouldRetryErrorFunc: shouldRetryError([]string{"429"})},
@cbruno10 I have fixed the formatting in dd6405fbfcb5ace6d3b7caba090b6816ae21989a

I have now added the `shouldRetryError` function to the `DefaultRetryConfig` which applies it across all the tables.

2022-11-23 23:54 UTC, cbruno10 approved these changes

2022-11-24 05:33 UTC, merged